flags:
  semigroups:
    bytestring-builder: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-1.0.2.1
- attoparsec-0.13.1.0
- base-compat-0.9.1
- call-stack-0.1.0
- fail-4.9.0.0
- hspec-2.3.2
- hspec-core-2.3.2
- hspec-discover-2.3.2
- hspec-expectations-0.8.2
- http-client-0.5.4
- http-client-tls-0.3.3
- http-types-0.9.1
- scientific-0.3.4.9
- semigroups-0.18.2
- tagged-0.8.4
- vector-0.11.0.0
resolver: lts-3.12
